server:
 port: 8210
spring:
 application:
  name: quartz-cluster2
  
# db 属性配置
 datasource:
#  type: com.alibaba.druid.pool.DruidDataSource
#  driver-class-name: oracle.jdbc.driver.OracleDriver
  url: jdbc:oracle:thin:@192.168.99.100:1521:xe
  username: baseweb
  password: baseweb
  
 jpa:
  hibernate:
#    ddl-auto: create #ddl-auto:设为create表示每次都重新建表
    ddl-auto: update #ddl-auto:设为update表示每次都不会重新建表
    dialect: org.hibernate.dialect.Oracle12cDialect
  show-sql: true
  
# 打印日志
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.bjnja: DEBUG