server:
 port: 8085
eureka:
 client:
  serviceUrl:
   defaultZone: http://localhost:8081/eureka/
spring:
 application:
  name: service-feign
feign:
 hystrix:
  enabled: true

management:  
  security:  
    enabled: false    #关闭安全验证  
    
turbine.appConfig: service-feign,service-ribbon
turbine.aggregator.clusterConfig: default
turbine.clusterNameExpression: new String("default")
turbine.instanceUrlSuffix: /hystrix.stream