server:
 port: 8081
eureka:
 instance:
  hostname: localhost
  prefer-ip-address: true
 client:
  registerWithEureka: false
  fetchRegistry: false
  serviceUrl:
   defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

management:  
  security:  
    enabled: false    #关闭安全验证  